root: ./

​structure:
  readme: README.md
  summary: SUMMARY.md​

redirects:
  system/architecture: README.md
  technology/v3: technology/deployments.md
  technology/servers: technology/makers.md
  technology/request-for-quote: technology/protocols.md
  technology/last-look: technology/protocols.md
  guides/voters: README.md
  guides/ambassadors: README.md
  guides/authors: README.md
  technology/signatures: technology/formats.md
  community/onboarding: README.md
